services:
  cloud_store:
    image: cloud_store
    build:
      context: .
      dockerfile: Cloud_Store/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - USE_API=true