name: Build and Release

on:
  push:
    branches:
      - Repo-orga
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        architecture: [x64, arm]
        exclude:
          - os: windows-latest
            architecture: arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build for Ubuntu x64
        if: matrix.os == 'ubuntu-latest' && matrix.architecture == 'x64'
        run: dotnet publish -c Release -r linux-x64 --self-contained true

      - name: Build for Ubuntu ARM
        if: matrix.os == 'ubuntu-latest' && matrix.architecture == 'arm'
        run: dotnet publish -c Release -r linux-arm --self-contained true

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: dotnet publish -c Release -r win-x64 --self-contained true

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/myapp:latest .

      - name: Push Docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository }}/myapp:latest

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false